{
 "title": "Host System",
 "tags": [ "system" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_time_seconds,node)"
   },
   { "name": "tag", "query": "node" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power Status",
   "type": "singlestat",
   "description": "Power Status",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{$tag=\"$host\"}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "singlestat",
   "description": "Days has it been power on",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{$tag=\"$host\"} - node_boot_time_seconds{$tag=\"$host\"}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Status",
   "type": "singlestat",
   "description": "Status CPU Usage  Thresholds  value  will have :\nvalue < 50  = OK,\n50 < value  <= 70 = WRRN,\nvalue >70 = CRIT\n",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(100 - sum(rate(node_cpu_seconds_total{$tag=\"$host\",mode=\"idle\"}[5m]))  * 100 / count(node_cpu_seconds_total{$tag=\"$host\",mode=\"idle\"}))"
    }
   ]
  },
  {
   "title": "Memory Status",
   "type": "singlestat",
   "description": "Status Memory Usage  Thresholds  value  will have :\nvalue < 50  = OK,\n50 < value  <= 70 = WRRN,\nvalue >70 = CRIT\n",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(100 * (node_memory_MemTotal_bytes{$tag='$host'} - node_memory_MemFree_bytes{$tag='$host'} )) / node_memory_MemTotal_bytes{$tag='$host'}",
     "legendFormat": "Memory-Usage"
    }
   ]
  },
  {
   "title": "Disk Status",
   "type": "singlestat",
   "description": "Status DiskUsage  Thresholds  value  will have :\nvalue < 50  = OK,\n50 < value  <= 70 = WRRN,\nvalue >70 = CRIT\n",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * ((node_filesystem_size_bytes{device=~\"/dev/.+\",fstype=\"ext4\",mountpoint=\"/\",$tag=\"$host\"}\t - node_filesystem_free_bytes{$tag=\"$host\",device!=\"tmpfs\",device!=\"rootfs\"}) / node_filesystem_size_bytes{device=~\"/dev/.+\",fstype=\"ext4\",mountpoint=\"/\",$tag=\"$host\"})"
    }
   ]
  },
  {
   "title": "% CPU Usage",
   "type": "gauge",
   "description": "% CPU Usage  Thresholds  value  will have :\nvalue < 50%  = OK,\n50% < value  <= 70% = WRRN,\nvalue >70% = CRIT\n",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(100 - sum(rate(node_cpu_seconds_total{$tag=\"$host\",mode=\"idle\"}[5m]))  * 100 / count(node_cpu_seconds_total{$tag=\"$host\",mode=\"idle\"}))"
    }
   ]
  },
  {
   "title": "% Memory Usage",
   "type": "gauge",
   "description": "% Memory Usage(use + cash  + buffer)  Thresholds  value  will have :\nvalue < 50  = OK,\n50 < value  <= 70 = WRRN,\nvalue >70 = CRIT\n\n",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "(100 * (node_memory_MemTotal_bytes{$tag='$host'} - node_memory_MemFree_bytes{$tag='$host'} )) / node_memory_MemTotal_bytes{$tag='$host'}",
     "legendFormat": "Memory-Usage"
    }
   ]
  },
  {
   "title": "% Disk Space Usage",
   "type": "singlestat",
   "description": "% Disk Space Usage  Thresholds  value  will have :\nvalue < 50  = OK,\n50 < value  <= 70 = WRRN,\nvalue >70 = CRIT\n\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * ((node_filesystem_size_bytes{device=~\"/dev/.+\",fstype=\"ext4\",mountpoint=\"/\",$tag=\"$host\"}\t - node_filesystem_free_bytes{$tag=\"$host\",device!=\"tmpfs\",device!=\"rootfs\"}) / node_filesystem_size_bytes{device=~\"/dev/.+\",fstype=\"ext4\",mountpoint=\"/\",$tag=\"$host\"})",
     "legendFormat": "Disk_{{device}}_Usage"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "singlestat",
   "description": "Virtual CPUs",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{$tag=\"$host\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "description": "Memory Usage (use + cash  + buffer)  \n\n",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{$tag='$host'} - node_memory_MemFree_bytes{$tag='$host'}",
     "legendFormat": "Memory-Usage"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "singlestat",
   "description": "Memory Total\n\n",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{$tag='$host'}",
     "legendFormat": "Memory-Usage"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "description": "Disk  Usage \n\n",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=~\"/dev/.+\",fstype=\"ext4\",mountpoint=\"/\",$tag=\"$host\"}\t - node_filesystem_free_bytes{$tag=\"$host\",device!=\"tmpfs\",device!=\"rootfs\"}",
     "legendFormat": "Memory-Usage"
    }
   ]
  },
  {
   "title": "DiskTotal",
   "type": "singlestat",
   "description": "Disk Total\n\n",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=~\"/dev/.+\",fstype=\"ext4\",mountpoint=\"/\",$tag=\"$host\"}\t",
     "legendFormat": "Memory-Total"
    }
   ]
  },
  {
   "title": "% CPU Usage",
   "type": "graph",
   "description": "% CPU Usage ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(100 - sum(rate(node_cpu_seconds_total{$tag=\"$host\",mode=\"idle\"}[5m]))  * 100 / count(node_cpu_seconds_total{$tag=\"$host\",mode=\"idle\"}))",
     "legendFormat": "CPU-Usage"
    }
   ]
  },
  {
   "title": "% Memory Usage",
   "type": "graph",
   "description": "% Memory Usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(100 * (node_memory_MemTotal_bytes{$tag='$host'} - node_memory_MemFree_bytes{$tag='$host'} )) / node_memory_MemTotal_bytes{$tag='$host'}",
     "legendFormat": "Memory-Usage"
    }
   ]
  },
  {
   "title": "% Disk Space Used",
   "type": "graph",
   "description": "% Disk Space Used",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * ((node_filesystem_size_bytes{$tag=\"$host\",device!=\"tmpfs\",device!=\"rootfs\"} - node_filesystem_free_bytes{$tag=\"$host\",device!=\"tmpfs\",device!=\"rootfs\"}) / node_filesystem_size_bytes{$tag=\"$host\",device !=\"tmpfs\",device!=\"rootfs\"})",
     "legendFormat": "Disk_{{device}}_Usage"
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU Detail",
   "type": "graph",
   "description": "CPU Detail % Usage\n",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{$tag=\"$host\"}[5m])) by (mode) * 100 / count(node_cpu_seconds_total{$tag=\"$host\"}) by (mode) or sum(irate(node_cpu_seconds_total{$tag=\"$host\"}[5m])) by (mode) * 100 / count(node_cpu_seconds_total{$tag=\"$host\"}) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{$tag=\"$host\"} - (node_memory_MemFree_bytes{$tag=\"$host\"} + node_memory_Buffers_bytes{$tag=\"$host\"} + node_memory_Cached_bytes{$tag=\"$host\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{$tag=\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{$tag=\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{$tag=\"$host\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemTotal_bytes{$tag=\"$host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{$tag=\"$host\", device!=\"lo\"}[5s]) or irate(node_network_receive_bytes_total{$tag=\"$host\", device!=\"lo\"}[5m])"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{$tag=\"$host\", device!=\"lo\"}[5s]) or irate(node_network_transmit_bytes_total{$tag=\"$host\", device!=\"lo\"}[5m])"
    }
   ]
  },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{$tag=\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{$tag=\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{$tag=\"$host\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{$tag=\"$host\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{$tag=\"$host\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "I/O Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pgpgin{$tag=\"$host\"}[5s]) * 1024 or irate(node_vmstat_pgpgin{$tag=\"$host\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "expr": "rate(node_vmstat_pgpgout{$tag=\"$host\"}[5s]) * 1024 or irate(node_vmstat_pgpgout{$tag=\"$host\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_procs_running{$tag=\"$host\"}",
     "legendFormat": "Processes in runnable state"
    },
    {
     "expr": "node_procs_blocked{$tag=\"$host\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{$tag=\"$host\"} - node_memory_SwapFree_bytes{$tag=\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapFree_bytes{$tag=\"$host\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{$tag=\"$host\"}[5s]) * 4096 or irate(node_vmstat_pswpin{$tag=\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap In"
    },
    {
     "expr": "rate(node_vmstat_pswpout{$tag=\"$host\"}[5s]) * 4096 or irate(node_vmstat_pswpout{$tag=\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap Out"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_forks_total{$tag=\"$host\"}[5s]) or irate(node_forks_total{$tag=\"$host\"}[5m])",
     "legendFormat": "Forks"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_context_switches_total{$tag=\"$host\"}[5s]) or irate(node_context_switches_total{$tag=\"$host\"}[5m])",
     "legendFormat": "Context Switches"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(node_intr_total{$tag=\"$host\"}[5s]) or irate(node_intr_total{$tag=\"$host\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  }
 ]
}